# Generated by Django 5.1.4 on 2026-07-11 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='is_assembly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='quotation.quotationitem'),
        ),
    ]
