# Generated by Django 5.1.4 on 2026-07-02 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyproduct',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_products_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assemblyproductitem',
            name='assembly_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_product_items', to='inventory.assemblyproduct'),
        ),
        migrations.AddField(
            model_name='assemblyproductitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_product_items_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='assemblyproductitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_product_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='inventory.stockmovement'),
        ),
        migrations.AlterUniqueTogether(
            name='assemblyproduct',
            unique_together={('name', 'barcode')},
        ),
        migrations.AlterUniqueTogether(
            name='assemblyproductitem',
            unique_together={('assembly_product', 'product')},
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['type'], name='inventory_i_type_50c302_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['created_at'], name='inventory_i_created_108a29_idx'),
        ),
    ]
