# Generated by Django 5.1.4 on 2026-07-02 18:11

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits (e.g., 9876543210).', regex='^\\d{10}$')])),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('view_dashboard', 'view dashboard'), ('download_report', 'download report')],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(help_text='The invoice number from the supplier.', max_length=100)),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice_type', models.CharField(choices=[('GST_APPLICABLE', 'GST Applicable'), ('LOCAL_PURCHASE', 'Local Purchase')], default='GST_APPLICABLE', max_length=20)),
                ('gst_type', models.CharField(blank=True, choices=[('CGST_SGST', 'CGST/SGST'), ('IGST', 'IGST')], default='IGST', help_text='Specify GST type if applicable.', max_length=20, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The total amount before taxes.', max_digits=12)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='For CGST/SGST type, SGST is assumed to be the same as this amount.', max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The grand total amount including all taxes.', max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Bank transaction reference number.', max_length=100, null=True)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
