# Generated by Django 5.1.4 on 2026-07-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='purchased_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
